# Workflow for building and deploying the Jupyter Book documentation
# This workflow is triggered on push events and performs the following tasks:
# 1. Builds Jupyter Book documentation from notebook files
# 2. Builds Marimo interactive notebooks and exports them to HTML-WASM format
# 3. Combines all artifacts and deploys them to GitHub Pages

name: deploy-book

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main


# Default permissions for all jobs
# Restricting to read-only access for security, with specific permissions granted where needed
permissions:
  contents: read

# This workflow contains multiple jobs that run in parallel and sequentially
jobs:
  # Job to build Marimo interactive notebooks and export them to HTML-WASM
  # This creates interactive web applications from Python notebook files
  marimo:
    runs-on: ubuntu-latest
    steps:
      - uses: tschm/marimushka/actions/export@main

  # The deploy job publishes the built site to GitHub Pages
  deploy:
    needs: marimo  # This job depends on the build job completing successfully

    # Required permissions for the GitHub Pages deployment
    permissions:
      pages: write      # Permission to deploy to Pages
      id-token: write   # Permission to verify the deployment

    # Configure the deployment environment
    environment:
      name: github-pages                             # Deploy to the github-pages environment
      url: ${{ steps.deployment.outputs.page_url }}  # Use the URL from the deployment step

    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      # Deploy the site to GitHub Pages using the official action
      - name: 🚀 Deploy to GitHub Pages
        id: deployment                 # ID used to reference this step's outputs
        uses: actions/deploy-pages@v4  # GitHub's official Pages deployment action
