# Workflow for building and deploying the Jupyter Book documentation
# This workflow is triggered on push events and performs the following tasks:
# 1. Builds Jupyter Book documentation from notebook files
# 2. Builds Marimo interactive notebooks and exports them to HTML-WASM format
# 3. Combines all artifacts and deploys them to GitHub Pages

name: deploy-book

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main


# Default permissions for all jobs
# Restricting to read-only access for security, with specific permissions granted where needed
permissions:
  contents: read

# This workflow contains multiple jobs that run in parallel and sequentially
jobs:
  # Job to build Marimo interactive notebooks and export them to HTML-WASM
  # This creates interactive web applications from Python notebook files
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - uses: tschm/marimushka/actions/export@v0.0.8
        with:
          notebooks: 'notebooks'

  # Job to combine all artifacts and prepare them for deployment
  # This job runs after both jupyter and marimo jobs have completed
  deploy:
    runs-on: ubuntu-latest

    needs: [marimo]  # This job depends on both jupyter and marimo jobs

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Publish book
        id: deployment
        uses: tschm/cradle/actions/book@v0.1.71
