# Workflow for creating a new version release
# This workflow is manually triggered to create a new version tag for the EPFL project
# Unlike other workflows, this one only creates a tag and does not deploy to GitHub Pages

name: Bump version and publish

# Trigger the workflow manually using the GitHub Actions UI
# This allows controlled releases when needed rather than on every push
on:
  workflow_dispatch:


jobs:
  # Job to generate a new version tag based on semantic versioning
  # This is a simple workflow with just one job to create a new version tag
  tag:
    # Permission to write to repository contents (needed to create tags)
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      # Use the cradle/actions/tag action to generate a semantic version tag
      # This automatically determines the next version number based on commit messages
      # Note: This uses v0.1.68 which is slightly older than the version used in other workflows
      - name: Generate Tag
        uses: tschm/cradle/actions/tag@v0.1.72
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
