# Workflow for running tests for the project
# This workflow is triggered on push and pull request events
# It runs the pytest tests to ensure code quality and functionality

name: run-tests

# Trigger the workflow on push and pull request events
# This ensures tests are run whenever code changes are pushed or a PR is created
on:
  push


# Default permissions for all jobs
# Restricting to read-only access for security
permissions:
  contents: read

# This workflow contains a single job to run the tests
jobs:
  # Job to run the pytest tests
  tests:
    runs-on: ubuntu-latest
    steps:
      # Set up the Python virtual environment with all required dependencies
      # This uses a reusable action from the cradle repository
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71

      # Install additional dependencies needed for testing
      - name: Install test dependencies
        run: |
          uv run pip install --no-cache-dir pytest requests marimo

      # Run the tests using pytest
      - name: Run tests
        run: |
          uv run pytest -xvs tests
